services:
  app:
    container_name: "lanchonete-cadastros"
    build:
      context: .
      dockerfile: Dockerfile
      target: development-cadastros
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 7001
      NODE_ENV: dev
      DATABASE_URL: postgresql://postgres:postgres@db:5431/lanchonete?schema=public
    ports:
      - 7001:7001
    command: sh -c "npx prisma migrate deploy && npm run dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonete
    expose:
      - 5431
    ports:
      - 5431:5431
    command: -p 5431
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-cadastros"
    ports:
      - "8081:8081"
    volumes:
      - ./tooling/swagger/swagger.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
    default:
        name: lanchonete-network
