services:
  app:
    image: leoeareis/lanchonete-cadastros:v1
    environment:
      PORT: 7000
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/lanchonete?schema=public
    ports:
      - 7000:7000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonete
    ports:
      - 5432:5432

networks:
    default:
        name: lanchonete-network
